### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by chrisbensch** [mikaelkall/massrecon#5]
I've installed the current git version in Kali 2020.1a and also in Docker from python:3.8-slim-buster.  Here is the error when trying to run:

root@2088475b6ca3:/opt/massrecon# python3 massrecon.py recon 10.10.10.171
Traceback (most recent call last):
  File "massrecon.py", line 68, in <module>
    Librecon().run(ip=ip)
  File "/opt/massrecon/librecon/librecon.py", line 29, in run
    np = Nmap(hostname=ip)
  File "/opt/massrecon/librecon/nmap.py", line 37, in __init__
    self.chr = CherryTree(address=hostname)
  File "/opt/massrecon/librecon/cherrytree.py", line 607, in __init__
    cfg = Configuration()
  File "/opt/massrecon/librecon/configuration.py", line 28, in __init__
    self.create_default_config()
  File "/opt/massrecon/librecon/configuration.py", line 50, in create_default_config
    self.config.set('oscp', 'email', 'xxxx@xxxx.com')
  File "/usr/local/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/local/lib/python3.8/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'oscp'

**Comment by mikaelkall** [comment]
Sorry for the inconvenience! The develop branch is a bit unstable as I do a lot of experimentation in that so it is not always in a working state. Understand it adds a bit confusion as Github pre-select develop branch at the moment, I will fix that as soon I get latest stable release into master.  

Your issue is that missing these values in ~/.massrecon/massrecon.ini

```sh
[oscp]
email = xxxx@xxxx.com
osid = OS-XXXXX
```
The intention was the tool template these sections if you don't have them, but it did not work as the code that add the section was missing. I have now fixed that so if you re-clone or pull the latest changed it should now work. You may need to delete ~/.massrecon/massrecon.ini to get the settings templated if you don't add them manually into the file.

Note this feature I experiment with is to automatically generate OSCP report from the CherryTree data. To save somve time when do the report-writing. At the moment it only import ip addresses as I have lost the motivation a bit to finish it as I'm done with my OSCP. However if a lot of people is interested in that feature I may continue in develop it.  

This tool is mostly done for myself in my OSCP but as I'm not doing it anymore the project is a bit stalled, but I may pickup this again as I seen a lot of people is interested in it.
